openapi: 3.0.0
info:
  title: Consumer API
  description:
  version: 1.0.0
servers:
  - url: http://localhost:3000/v1
    description: Local Development Server
    variables:
      basePath:
        default: v1
  - url: https://staging.cat-api.domain.com/v1
    description: Staging Server
    variables:
      basePath:
        default: v1
  - url: https://cat-api.domain.com/v1
    description: Production Server
    variables:
      basePath:
        default: v1

components:
  securitySchemes:
    bearerAuth:
      type: apiKey
      name: Bearer
      in: header

    cookieAuth:
      type: apiKey
      in: cookie
      name: Backend-Starter-<Environment>

security:
  - bearerAuth: []
  - cookieAuth: []

paths:
  /cats:
    $ref: "../cat/cat.doc.yml#/components"
  /cats/:ID:
    $ref: "../cat/cat-details.doc.yml#/components"
